(function(g){var window=this;var Qpa=function(a,b){return g.Tb(a,b)},D5=function(){},Rpa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Pb(a)},Spa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Gd&&"function"==typeof a.Gd)var c=a.Gd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.La(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Qb(a);d=Rpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},E5=function(a){g.ln(a,"zx",g.ad());
return a},F5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.qn(a.l,b,c)},G5=function(a){return(a=g.Ko(a))?new ActiveXObject(a):new XMLHttpRequest},H5=function(a,b){return b+" ["+a.aa+" "+a.F+" "+a.getStatus()+"]"},Tpa=function(a){return"content-type"==a.toLowerCase()},I5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},Upa=function(a){return g.Ld&&g.md(9)&&g.Ea(a.timeout)&&g.Ca(a.ontimeout)},J5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},K5=function(a,b){if(a.g){I5(a);
var c=a.g,d=a.P[0]?g.Ga:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},L5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;J5(a);K5(a)},M5=function(a){return a.g?a.g.readyState:0},N5=function(a){if(a.i&&"undefined"!=typeof g.AY)if(a.P[1]&&4==M5(a)&&2==a.getStatus())H5(a,"Local request error detected and ignored");
else if(a.D&&4==M5(a))g.Hg(a.Wv,0,a);else if(a.dispatchEvent("readystatechange"),4==M5(a)){H5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Rg(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Vpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<M5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";J5(a)}}finally{K5(a)}}},O5=function(a){g.Rf.call(this);
this.headers=new g.$m;this.M=a||null;this.i=!1;this.P=this.g=null;this.aa=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Z="";this.I=this.R=!1},P5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Wpa=function(a,b){var c=[];
g.Vk(b,function(d){try{var e=g.Zo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Yo(e)&&c.push(d):c.push(d)},a);
return c},Xpa=function(a,b){var c=Wpa(a,b);
(0,g.B)(c,function(d){g.Zo.prototype.remove.call(this,d)},a)},Q5=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},Ypa=function(a,b){g.$a(a,b)||a.push(b)},R5=function(a){var b=0,c;
for(c in a)b++;return b},S5=function(a,b){var c=b instanceof g.wc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.xc(c)},Zpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},$pa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(Zpa(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},aqa=function(a,b,c,d){var e=new g.cn(null,void 0);
a&&g.dn(e,a);b&&g.en(e,b);c&&g.fn(e,c);d&&(e.i=d);return e},T5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return $pa(a)},U5=function(){this.g=[];
this.i=[]},V5=function(a,b){g.dq[a]=!0;
var c=g.bq();c&&c.publish.apply(c,arguments);g.dq[a]=!1},W5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.$m;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",bqa(this,a.capabilities||""),cqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},bqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(Qpa,dqa)).forEach(function(c){a.capabilities.add(c)})},cqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},X5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},Y5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Z5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},eqa=function(a){return new X5(a)},$5=function(a){return g.Ka(a)?(0,g.G)(a,eqa):[]},a6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},b6=function(a){return g.Ka(a)?"["+(0,g.G)(a,a6).join(",")+"]":"null"},c6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},fqa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},d6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},e6=function(a,b){return g.Xa(a,function(c){return Y5(c,b)})},gqa=function(){var a=(0,g.ut)();
a&&Xpa(a,a.g.jf(!0))},f6=function(){var a=g.xt("yt-remote-connected-devices")||[];
g.pb(a);return a},hqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},g6=function(a){g.wt("yt-remote-connected-devices",a,86400)},i6=function(){if(h6)return h6;
var a=g.xt("yt-remote-device-id");a||(a=c6(),g.wt("yt-remote-device-id",a,31536E3));for(var b=f6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return h6=d},j6=function(){var a=f6(),b=i6();
g.$a(a,b);g.At()&&g.rb(a,b);a=hqa(a);if(0==a.length)try{g.ys("remote_sid")}catch(c){}else try{g.xs("remote_sid",a.join(","),-1)}catch(c){}},k6=function(){return g.xt("yt-remote-session-browser-channel")},l6=function(){return g.xt("yt-remote-local-screens")||[]},m6=function(){g.wt("yt-remote-lounge-token-expiration",!0,86400)},iqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(l6(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.kj)(c,function(d){return!g.$a(b,d)})&&m6();
g.wt("yt-remote-local-screens",a,31536E3)},jqa=function(a,b){g.wt("yt-remote-session-browser-channel",a);
g.wt("yt-remote-session-screen-id",b);var c=f6(),d=i6();g.$a(c,d)||c.push(d);g6(c);j6()},n6=function(a){a||(g.zt("yt-remote-session-screen-id"),g.zt("yt-remote-session-video-id"));
j6();a=f6();g.cb(a,i6());g6(a)},p6=function(){if(!o6){var a=g.ip();
a&&(o6=new g.To(a))}return o6?!!o6.get("yt-remote-use-staging-server"):!1},q6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},r6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?s6(a.shift(),function(){t6(a)}):u6()},kqa=function(a){return"chrome-extension://"+a+v6},s6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=r6();
a&&a(!1,"No cast extension found")},w6=function(){if(lqa){var a=2,b=r6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;s6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},mqa=function(){w6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+v6,"//www.gstatic.com/eureka/clank"+v6])},x6=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Vc=b;this.u=(0,g.y)(this.bD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},y6=function(){},z6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ba=new g.rn(this);this.i=new g.Gg;this.i.setInterval(250)},B6=function(a,b,c){a.ai=1;
a.kg=E5(b.clone());a.sh=c;a.u=!0;A6(a,null)},C6=function(a,b,c,d,e){a.ai=1;
a.kg=E5(b.clone());a.sh=null;a.u=c;e&&(a.Sz=!1);A6(a,d)},A6=function(a,b){a.Fi=(0,g.D)();
D6(a);a.Bg=a.kg.clone();F5(a.Bg,"t",a.A);a.Wk=0;a.tc=a.g.hp(a.g.Mk()?b:null);0<a.Op&&(a.yn=new g.Ll((0,g.y)(a.YA,a,a.tc),a.Op));a.ba.da(a.tc,"readystatechange",a.JL);var c=a.Xg?g.ac(a.Xg):{};a.sh?(a.fo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Bg,a.fo,a.sh,c)):(a.fo="GET",a.Sz&&!g.Nd&&(c.Connection="close"),a.tc.send(a.Bg,a.fo,null,c));a.g.re(1)},K6=function(a,b,c){for(var d=!0;!a.Ng&&a.Wk<c.length;){var e=nqa(a,c);
if(e==E6){4==b&&(a.lg=4,F6(15),d=!1);break}else if(e==G6){a.lg=4;F6(16);d=!1;break}else H6(a,e)}4==b&&0==c.length&&(a.lg=1,F6(17),d=!1);a.xe=a.xe&&d;d||(I6(a),J6(a))},nqa=function(a,b){var c=a.Wk,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return G6;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.Wk=d+c;return e},N6=function(a,b){a.Fi=(0,g.D)();
D6(a);var c=b?window.location.hostname:"";a.Bg=a.kg.clone();g.ln(a.Bg,"DOMAIN",c);g.ln(a.Bg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){I6(a);a.lg=7;F6(22);J6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in L6)k=L6[l];else if(l in M6)k=L6[l]=M6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
L6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Qc(g.pc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Lc(c));a.Be.close();a.Be.parentWindow.m=(0,g.y)(a.eL,a);a.Be.parentWindow.d=(0,g.y)(a.Xy,a,!0);a.Be.parentWindow.rpcClose=(0,g.y)(a.Xy,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Bc(a.Bg.toString());d=g.Xc(g.yc(d));d=g.Qc(g.pc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Rc(c,d);a.g.re(1)},D6=function(a){a.Ts=(0,g.D)()+a.o;
O6(a,a.o)},O6=function(a,b){if(null!=a.Vi)throw Error("WatchDog timer not null");
a.Vi=P6((0,g.y)(a.oL,a),b)},Q6=function(a){a.Vi&&(g.w.clearTimeout(a.Vi),a.Vi=null)},J6=function(a){a.g.Uv()||a.Ng||a.g.hn(a)},I6=function(a){Q6(a);
g.of(a.yn);a.yn=null;a.i.stop();g.tn(a.ba);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},H6=function(a,b){try{a.g.Ry(a,b),a.g.re(4)}catch(c){}},S6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;R6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){S6(a,b,c,d,f)},f)})}},R6=function(a,b,c){var d=new Image;
d.onload=function(){try{T6(d),c(!0)}catch(e){}};
d.onerror=function(){try{T6(d),c(!1)}catch(e){}};
d.onabort=function(){try{T6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{T6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
S5(d,a)},T6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},U6=function(a){this.g=a;
this.i=new y6},W6=function(a){var b=V6(a.g,a.dj,"/mail/images/cleardot.gif");
E5(b);S6(b.toString(),5E3,(0,g.y)(a.nC,a),3,2E3);a.re(1)},Y6=function(a){var b=a.g.F;
if(null!=b)F6(5),b?(F6(11),X6(a.g,a,!1)):(F6(12),X6(a.g,a,!0));else if(a.Cd=new z6(a,void 0,void 0,void 0),a.Cd.Xg=a.Mp,b=a.g,b=V6(b,b.Mk()?a.Ij:null,a.Np),F6(5),!g.Ld||g.nd(10))F5(b,"TYPE","xmlhttp"),C6(a.Cd,b,!1,a.Ij,!1);else{F5(b,"TYPE","html");var c=a.Cd;a=!!a.Ij;c.ai=3;c.kg=E5(b.clone());N6(c,a)}},Z6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new y6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},oqa=function(a,b){this.g=a;
this.map=b;this.context=null},$6=function(a){g.qf.call(this,"statevent",a)},a7=function(a,b){g.qf.call(this,"timingevent",a);
this.size=b},b7=function(a){g.qf.call(this,"serverreachability",a)},f7=function(a){c7(a);
if(3==a.g){var b=a.tk++,c=a.Wl.clone();g.ln(c,"SID",a.l);g.ln(c,"RID",b);g.ln(c,"TYPE","terminate");d7(a,c);b=new z6(a,a.l,b,void 0);b.ai=2;b.kg=E5(c.clone());S5(new Image,b.kg.toString());b.Fi=(0,g.D)();D6(b)}e7(a)},h7=function(a){a.DC(1,0);
a.Wl=V6(a,null,a.Lp);g7(a)},c7=function(a){a.ag&&(a.ag.abort(),a.ag=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.lf&&(g.w.clearTimeout(a.lf),a.lf=null);i7(a);a.zd&&(a.zd.cancel(),a.zd=null);a.gg&&(g.w.clearTimeout(a.gg),a.gg=null)},j7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new oqa(a.pH++,b));2!=a.g&&3!=a.g||g7(a)},g7=function(a){a.zd||a.gg||(a.gg=P6((0,g.y)(a.Wy,a),0),a.Uh=0)},m7=function(a,b){if(1==a.g){if(!b){a.tk=Math.floor(1E5*Math.random());
var c=a.tk++,d=new z6(a,"",c,void 0);d.Xg=null;var e=k7(a),f=a.Wl.clone();g.ln(f,"RID",c);g.ln(f,"CVER","1");d7(a,f);B6(d,f,e);a.zd=d;a.g=2}}else 3==a.g&&(b?l7(a,b):0==a.i.length||a.zd||l7(a))},l7=function(a,b){if(b)if(6<a.Og){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.tk-1;var d=k7(a)}else c=b.B,d=b.sh;else c=a.tk++,d=k7(a);var e=a.Wl.clone();g.ln(e,"SID",a.l);g.ln(e,"RID",c);g.ln(e,"AID",a.ki);d7(a,e);c=new z6(a,a.l,c,a.Uh+1);c.Xg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.zd=c;B6(c,e,d)},d7=function(a,b){if(a.Tc){var c=a.Tc.zv();
c&&g.Jb(c,function(d,e){g.ln(b,e,d)})}},k7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Og&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Og?e:f-d;try{g.Jb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},n7=function(a){a.Sb||a.lf||(a.B=1,a.lf=P6((0,g.y)(a.Vy,a),0),a.Nh=0)},p7=function(a){if(a.Sb||a.lf||3<=a.Nh)return!1;
a.B++;a.lf=P6((0,g.y)(a.Vy,a),o7(a,a.Nh));a.Nh++;return!0},X6=function(a,b,c){a.co=c;
a.Je=b.yf;a.A||h7(a)},i7=function(a){null!=a.Sg&&(g.w.clearTimeout(a.Sg),a.Sg=null)},o7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},r7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.y)(a.nM,a);c||(c=new g.cn("//www.google.com/images/cleardot.gif"),E5(c));R6(c.toString(),1E4,d)}else F6(2);q7(a,b)},q7=function(a,b){a.g=0;
a.Tc&&a.Tc.wu(b);e7(a);c7(a)},e7=function(a){a.g=0;
a.Je=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Uo();else{g.fb(a.o);var b=g.fb(a.i);a.o.length=0;a.i.length=0;a.Tc.Uo(b)}},V6=function(a,b,c){var d=g.mn(c);
if(""!=d.g)b&&g.en(d,b+"."+d.g),g.fn(d,d.u);else{var e=window.location;d=aqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.qj&&g.Jb(a.qj,function(f,k){g.ln(d,k,f)});
g.ln(d,"VER",a.Og);d7(a,d);return d},P6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},F6=function(a){s7.dispatchEvent(new $6(s7,a))},t7=function(){},pqa=function(a,b){this.action=a;
this.params=b||{}},u7=function(a,b){g.H.call(this);
this.g=new g.N(this.WK,0,this);g.I(this,this.g);this.Vc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},v7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.So;this.i=new u7(this.SL,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},qqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.co,sessionId:a.g.l,arrayId:a.g.ki}},w7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&m7(a.g),f7(a.g));a.D=0},x7=function(a){return!!a.g&&3==a.g.g},rqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},y7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Ug(a)||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gb(a,"10.0")&&(this.i=!1))},z7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},A7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),qd:g.Qa(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Wq(b,a)},tqa=function(){var a=B7;
C7();D7.push(a);sqa(D7)},E7=function(a,b){C7();
var c=D7,d=uqa(a,String(b));0==c.length?vqa(d):(sqa(c),(0,g.B)(c,function(e){e(d)}))},C7=function(){D7||(D7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",D7,void 0))},vqa=function(a){var b=(F7+1)%50;
F7=b;G7[b]=a;H7||(H7=49==b)},sqa=function(a){var b=G7;
if(b[0]){var c=F7,d=H7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
G7=Array(50);F7=-1;H7=!1}},uqa=function(a,b){var c=((0,g.D)()-wqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},I7=function(a){g.Q.call(this);
this.B=a;this.g=[]},xqa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},yqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!d6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=xqa(a,b[d])||c;return c},zqa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},J7=function(a,b,c,d){g.Q.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},L7=function(a){I7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;K7(this);this.info("Initializing with "+b6(this.g))},Aqa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=z7(a.l,"/pairing/get_lounge_token_batch");
A7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.lD,a),(0,g.y)(a.kD,a))}},K7=function(a){var b=$5(l6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return yqa(a,b)},M7=function(a,b){iqa((0,g.G)(a.g,Z5));
b&&m6()},O7=function(a,b){g.Q.call(this);
this.A=b;var c=g.xt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;N7("Initialized with "+g.Lg(this.g))},Bqa=function(a,b,c){var d=z7(a.u,"/pairing/get_screen_availability");
A7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},P7=function(a,b){a:if(R5(b)!=R5(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(N7("Updated online screens: "+g.Lg(a.g)),a.g=b,a.N("screenChange"));Cqa(a)},Q7=function(a){isNaN(a.l)||g.aq(a.l);
a.l=g.Zp((0,g.y)(a.Sr,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},N7=function(a){E7("OnlineScreenService",a)},Dqa=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},Cqa=function(a){a=g.Qb(g.Kb(a.g,function(b){return b}));
g.pb(a);a.length?g.wt("yt-remote-online-screen-ids",a.join(","),60):g.zt("yt-remote-online-screen-ids")},R7=function(a){I7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Eqa(this)},Gqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Id();if(k=(c?e6(k,c):null)||e6(k,b)){k.uuid=b;var l=S7(a,k);Bqa(a.i,l,function(m){e(m?l:null)})}else c?Fqa(a,c,(0,g.y)(function(m){var n=S7(this,new X5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Bqa(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},Hqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Fqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Wq(z7(a.A,"/pairing/get_lounge_token_batch"),e)},Iqa=function(a){a.g=a.l.Id();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+b6(a.g))},Eqa=function(a){T7(a);
a.l=new L7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.uD,a));Iqa(a);a.o=$5(g.xt("yt-remote-automatic-screen-cache")||[]);T7(a);a.info("Initializing automatic screens: "+b6(a.o));a.i=new O7(a.A,(0,g.y)(a.Id,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},S7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=e6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.wt("yt-remote-automatic-screen-cache",(0,g.G)(a.o,Z5)));T7(a);a.u[b.uuid]=b.id;g.wt("yt-remote-device-id-map",a.u,31536E3);return b},T7=function(a){a.u=g.xt("yt-remote-device-id-map")||{}},U7=function(a,b,c){g.Q.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},V7=function(a,b){E7(a.P,b)},W7=function(a,b){U7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.PM,this);this.u=(0,g.y)(this.zL,this);this.o=g.Zp((0,g.y)(function(){Jqa(this,null)},this),12E4)},Kqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Lg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ga,(0,g.y)(function(){V7(this,"Failed to send message: getMdxSessionStatus.")},a)):V7(a,"Sending yt message without session: "+g.Lg(b))},Jqa=function(a,b){g.aq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.jn,a),d=(0,g.y)(a.Md,a);a.Ov(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},X7=function(a,b,c){U7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ga;this.A=NaN;this.I=(0,g.y)(this.SM,this);this.g=g.Ga},Lqa=function(a){a.g=a.F.dB(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ga;
this.jn(b)},a),(0,g.y)(function(b){this.g=g.Ga;
this.Md(b)},a))},Mqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}p6()&&(b.env_useStageMdx=1);return g.ah(b)},Y7=function(a,b){U7.call(this,a,b,"ManualSession");
this.g=g.Zp((0,g.y)(this.mi,this,null),150)},Z7=function(a,b,c,d){g.Q.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.fK,this)},Nqa=function(a,b){return b?g.Xa(a.l,function(c){return Y5(b,c.label)},a):null},$7=function(a){E7("Controller",a)},B7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},a8=function(a){return a.u||!!a.l.length||!!a.g},b8=function(a,b,c){b!=a.g&&(g.of(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Uy,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.mi(null)):a.N("yt-remote-cast2-session-change",null))},Oqa=function(a){var b=a.i.cB(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&Y5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Nqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Uqa=function(a,b,c,d,e,f,k){Pqa()?Qqa(b,e,f,k)&&(d8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Rqa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Rqa(a,c):(e8("Failed to load cast API: "+m),f8(!1),d8(!1),g.zt("yt-remote-cast-available"),g.zt("yt-remote-cast-receiver"),Sqa(),c(!1))},d?g.lq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?mqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(w6(),t6(Tqa.map(kqa))))):c8("Cannot initialize because not running Chrome")},Sqa=function(){c8("dispose");
var a=g8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);Vqa(!1);g.gq(h8);h8.length=0},i8=function(){return!!g.xt("yt-remote-cast-installed")},Wqa=function(){var a=g.xt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Xqa=function(){c8("clearCurrentReceiver");
g.zt("yt-remote-cast-receiver")},Yqa=function(){return i8()?g8()?g8().getCastSession():(e8("getCastSelector: Cast is not initialized."),null):(e8("getCastSelector: Cast API is not installed!"),null)},k8=function(){i8()?g8()?j8()?(c8("Requesting cast selector."),g8().requestSession()):(c8("Wait for cast API to be ready to request the session."),h8.push(g.fq("yt-remote-cast2-api-ready",k8))):e8("requestCastSelector: Cast is not initialized."):e8("requestCastSelector: Cast API is not installed!")},l8=
function(a,b){j8()?g8().setConnectedScreenStatus(a,b):e8("setConnectedScreenStatus called before ready.")},Pqa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.ex||a},Zqa=function(a,b){g8().init(a,b)},Qqa=function(a,b,c,d){var e=!1;
g8()||(a=new Z7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.wt("yt-remote-cast-available",f);V5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){c8("onReceiverSelected: "+f.friendlyName);
g.wt("yt-remote-cast-receiver",f);V5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){c8("onReceiverResumed: "+f.friendlyName);
g.wt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){c8("onSessionChange: "+a6(f));
f||g.zt("yt-remote-cast-receiver");V5("yt-remote-cast2-session-change",f)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
c8("cloudview.createSingleton_: "+e);return e},g8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Rqa=function(a,b){f8(!0);
d8(!1);Zqa(a,function(c){c?(Vqa(!0),g.iq("yt-remote-cast2-api-ready")):(e8("Failed to initialize cast API."),f8(!1),g.zt("yt-remote-cast-available"),g.zt("yt-remote-cast-receiver"),Sqa());b(c)})},c8=function(a){E7("cloudview",a)},e8=function(a){E7("cloudview",a)},f8=function(a){c8("setCastInstalled_ "+a);
g.wt("yt-remote-cast-installed",a)},j8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Vqa=function(a){c8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},d8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},m8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Le=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},n8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Le=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},o8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},p8=function(a,b){a.B=b;
a.A=(0,g.D)()},q8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},r8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&n8(a)},s8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.g);b.hasPrevious=a.Le;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},u8=function(a,b){g.Q.call(this);
this.g=0;this.o=a;this.A=[];this.u=new U5;this.l=this.i=null;this.F=(0,g.y)(this.ZH,this);this.B=(0,g.y)(this.wk,this);this.D=(0,g.y)(this.YH,this);this.H=(0,g.y)(this.lI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ws,this),$qa(this))):c=3;0!=c&&(b?this.Ws(c):g.Zp((0,g.y)(function(){this.Ws(c)},this),0));
var d=Yqa();d&&t8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},v8=function(a){return new m8(a.o.getPlayerContextData())},$qa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.cK,b),this))},a)},ara=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},w8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},y8=function(a,b,c){var d=v8(a);
p8(d,c);-1E3!=d.playerState&&(d.playerState=b);x8(a,d)},z8=function(a,b,c){a.o.sendMessage(b,c)},x8=function(a,b){ara(a);
a.o.setPlayerContextData(s8(b));$qa(a)},t8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.wk(null));
a.l=b;a.l&&(E7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.wk(a.l.media[0]))},bra=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=v8(a);b.contentId!=d.videoId&&E7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;p8(d,a.i.getEstimatedTime());x8(a,d)}else E7("CP","No cast media video. Ignoring state update.")},A8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),z8(this,b,c))},a)},B8=function(a,b,c){g.Q.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Pa=this.g=null;this.na=a;this.O.push(g.cs(window,"beforeunload",(0,g.y)(this.eD,this)));this.i=[];this.Pa=new m8;this.V=b.id;this.g=cra(this,c);this.g.subscribe("handlerOpened",this.dI,this);this.g.subscribe("handlerClosed",this.aI,this);this.g.subscribe("handlerError",this.bI,this);this.g.subscribe("handlerMessage",this.cI,this);rqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.At()&&g.wt("yt-remote-session-video-id",d)},this)},C8=function(a){E7("conn",a)},cra=function(a,b){return new v7(z7(a.na,"/bc"),b)},D8=function(a,b){a.N("proxyStateChange",b)},dra=function(a){a.u=g.Zp((0,g.y)(function(){C8("Connecting timeout");
this.A(1)},a),2E4)},E8=function(a){g.aq(a.u);
a.u=NaN},F8=function(a){g.aq(a.P);
a.P=NaN},era=function(a){G8(a);
a.I=g.Zp((0,g.y)(function(){H8(this,"getNowPlaying")},a),2E4)},G8=function(a){g.aq(a.I);
a.I=NaN},gra=function(a,b){b&&(E8(a),F8(a));
b==(x7(a.g)&&isNaN(a.u))?b&&(D8(a,1),H8(a,"getSubtitlesTrack")):b?(a.R()&&a.Pa.reset(),D8(a,1),H8(a,"getNowPlaying"),fra(a)):a.A(1)},hra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Wb(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.N("remotePlayerChange"))},ira=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;r8(a.Pa,c,d);a.N("remoteQueueChange")},kra=function(a,b){b.params=b.params||{};
ira(a,b);jra(a,b);a.N("autoplayDismissed")},jra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
p8(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?era(a):G8(a);a.N("remotePlayerChange")},lra=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);p8(a.Pa,isNaN(c)?0:c);a.N("remotePlayerChange")}},mra=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.N("remotePlayerChange")},nra=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},ora=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Le="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.N("previousNextChange")},fra=function(a){g.aq(a.H);
a.H=g.Zp((0,g.y)(a.A,a,1),864E5)},H8=function(a,b,c){c?C8("Sending: action="+b+", params="+g.Lg(c)):C8("Sending: action="+b);
a.g.sendMessage(b,c)},I8=function(a){I7.call(this,"ScreenServiceProxy");
this.Hc=a;this.i=[];this.i.push(this.Hc.$_s("screenChange",(0,g.y)(this.MM,this)));this.i.push(this.Hc.$_s("onlineScreenChange",(0,g.y)(this.GJ,this)))},tra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Rp("MDX_CONFIG")||b;gqa();j6();J8||(J8=new y7(b?b.loungeApiHost:void 0),p6()&&(J8.g="/api/loungedev"));K8||(K8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",K8,void 0));pra();var c=L8();if(!c){var d=new R7(J8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=L8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Uqa(a,d,function(m){m?M8()&&l8(M8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){V5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),N8("Initializing: "+g.Lg(b)),O8.push(g.fq("yt-remote-cast2-availability-change",function(){V5("yt-remote-receiver-availability-change")})),O8.push(g.fq("yt-remote-cast2-receiver-selected",function(){P8(null);
V5("yt-remote-auto-connect","cast-selector-receiver")})),O8.push(g.fq("yt-remote-cast2-receiver-resumed",function(){V5("yt-remote-receiver-resumed","cast-selector-receiver")})),O8.push(g.fq("yt-remote-cast2-session-change",qra)),O8.push(g.fq("yt-remote-connection-change",function(m){m?l8(M8(),"YouTube TV"):Q8()||(l8(null,null),Xqa())})),a=R8(),b.isAuto&&(a.id+="#dial"),g.Nq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),N8(" -- with channel params: "+
g.Lg(a)),rra(a),c.start(),M8()||sra())},vra=function(){var a=ura();
i8()&&g.xt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},ura=function(){var a=L8().Hc.$_gos();
var b=S8();b&&T8()&&(d6(a,b)||a.push(b));return fqa(a)},U8=function(){var a=wra();
!a&&i8()&&Wqa()&&(a={key:"cast-selector-receiver",name:Wqa()});return a},wra=function(){var a=ura(),b=S8();
b||(b=Q8());return g.Xa(a,function(c){return b&&Y5(b,c.key)?!0:!1})},S8=function(){var a=M8();
if(!a)return null;var b=L8().Id();return e6(b,a)},qra=function(a){N8("remote.onCastSessionChange_: "+a6(a));
if(a){var b=S8();b&&b.id==a.id?l8(b.id,"YouTube TV"):(b&&V8(),W8(a,1))}else T8()&&V8()},V8=function(){j8()?g8().stopSession():e8("stopSession called before API ready.");
var a=T8();a&&(a.disconnect(1),X8(null))},Y8=function(){var a=T8();
return!!a&&3!=a.getProxyState()},N8=function(a){E7("remote",a)},L8=function(){if(!Z8){var a=g.x("yt.mdx.remote.screenService_");
Z8=a?new I8(a):null}return Z8},M8=function(){return g.x("yt.mdx.remote.currentScreenId_")},xra=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},yra=function(){return g.x("yt.mdx.remote.connectData_")},P8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},T8=function(){return g.x("yt.mdx.remote.connection_")},X8=function(a){var b=T8();
P8(null);a||xra("");g.Fa("yt.mdx.remote.connection_",a,void 0);K8&&((0,g.B)(K8,function(c){c(a)}),K8.length=0);
b&&!a?V5("yt-remote-connection-change",!1):!b&&a&&V5("yt-remote-connection-change",!0)},Q8=function(){var a=g.At();
if(!a)return null;var b=L8().Id();return e6(b,a)},W8=function(a,b){S8()&&S8();
xra(a.id);var c=new B8(J8,a,R8());c.connect(b,yra());c.subscribe("beforeDisconnect",function(d){V5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){T8()&&X8(null)});
X8(c)},sra=function(){var a=Q8();
a?(N8("Resume connection to: "+a6(a)),W8(a,0)):(n6(),Xqa(),N8("Skipping connecting because no session screen found."))},pra=function(){var a=R8();
if(g.Wb(a)){a=i6();var b=g.xt("yt-remote-session-name")||"",c=g.xt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},R8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},rra=function(a){a?(g.wt("yt-remote-session-app",a.app),g.wt("yt-remote-session-name",a.name)):(g.zt("yt-remote-session-app"),g.zt("yt-remote-session-name"));
g.Fa("yt.mdx.remote.channelParams_",a,void 0)},$8=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.Ls(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.YI);this.l.K(b,"captionschanged",this.XH);this.l.K(b,"captionssettingschanged",this.rA);this.l.K(b,"videoplayerreset",this.kn);this.l.K(b,"mdxautoplaycancel",this.mC);this.O=this.l.K(b,"onVolumeChange",this.Fy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Qy,this);c.subscribe("remotePlayerChange",this.yk,this);c.subscribe("remoteQueueChange",this.kn,this);c.subscribe("autoplayUpNext",this.ty,
this);c.subscribe("previousNextChange",this.Ny,this);c.subscribe("nowAutoplaying",this.Jy,this);c.subscribe("autoplayDismissed",this.ry,this);this.suggestion=null;this.F=new g.yC(64);this.o=new g.N(this.pA,500,this);g.I(this,this.o);this.A=new g.N(this.qA,1E3,this);g.I(this,this.A);this.I=new x6(this.wM,0,this);g.I(this,this.I);this.B={};this.P=new g.N(this.PA,1E3,this);g.I(this,this.P);this.H=new g.Ll(this.DF,1E3,this);g.I(this,this.H);this.M=g.Ga;this.rA();this.kn();this.yk()},a9=function(a,b){a.u.rd(b,
a.i.getVideoData().lengthSeconds)},zra=function(a){a9(a,0);
a.o.stop();b9(a,new g.yC(64))},d9=function(a,b){if(c9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.dc(c,b));a.g.fA(a.i.getVideoData(1).videoId,c);a.B=v8(a.g).g}},e9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Af,Q5(c));b9(a,new g.yC(1))},Ara=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{iQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},c9=function(a){return v8(a.g).videoId==a.i.getVideoData(1).videoId},b9=function(a,b){a.A.stop();
var c=a.F;if(!g.EC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.rK(a.i,d);a.F=b;Bra(a.u,c,b)}},f9=function(){g.W.call(this,{C:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{C:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{C:"div",G:"ytp-mdx-popup-title",U:"You're signed out"},{C:"div",G:"ytp-mdx-popup-description",U:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{C:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Cancel"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
U:"Confirm"}]}]}]});this.l=new g.nQ(this,250);g.I(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},g9=function(a){g.W.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.DP()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.nQ(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);Cra(this,g.nK(a))},Cra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.BN("Error on $RECEIVER_NAME",c):g.FC(b)||g.U(b,4)?g.BN("Playing on $RECEIVER_NAME",c):g.BN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.WT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.RK.call(this,a);
this.i={key:c6(),name:"This computer"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.ek=new g.yC(64);this.D=0;this.Bm=-1;if(!g.jz(g.X(this.player))){a=this.player;var b=g.rD(a);b&&(b=b.gk())&&(b=new h9(a,b),g.I(this,b));b=new g9(a);g.I(this,b);g.DK(a,b.element,4);this.F=new f9;g.I(this,this.F);g.DK(a,this.F.element,4)}},Bra=function(a,b,c){a.ek=c;
a.player.N("presentingplayerstatechange",new g.FD(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)V8();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Af,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=Q5(d))&&(c.locationInfo=d);d=c}else d=null;N8("Connecting to: "+g.Lg(b));"cast-selector-receiver"==b.key?
(P8(d||null),j8()?g8().setLaunchParams(d||null):e8("setLaunchParams called before ready.")):!d&&Y8()&&M8()==b.key?V5("yt-remote-connection-change",!0):(V8(),P8(d||null),d=L8().Id(),(d=e6(d,b.key))&&W8(d,1))}},Vpa=/^https?$/i,Dra=["POST",
"PUT"];g.A(O5,g.Rf);g.h=O5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.M?G5(this.M):G5(g.XY);this.P=this.M?this.M.getOptions():g.XY.getOptions();this.g.onreadystatechange=(0,g.y)(this.Wv,this);try{D5(H5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){D5(H5(this,"Error opening Xhr: "+f.message));L5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Spa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Gd(),Tpa);c=g.w.FormData&&a instanceof g.w.FormData;!g.$a(Dra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{I5(this),0<this.A&&(this.I=Upa(this.g),D5(H5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.Xv,this)):this.B=g.Hg(this.Xv,this.A,this)),D5(H5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){D5(H5(this,"Send error: "+f.message)),L5(this,f)}};
g.h.Xv=function(){"undefined"!=typeof g.AY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,H5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(H5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),K5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),K5(this,!0));O5.Ha.T.call(this)};
g.h.Wv=function(){this.ea()||(this.V||this.D||this.o?N5(this):this.eK())};
g.h.eK=function(){N5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<M5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var M6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},L6={"'":"\\'"},Era={};g.h=U5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Fma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var dqa={lN:"atp",wP:"ska",lP:"que",KO:"mus",vP:"sus",bO:"dsp",sP:"seq"};W5.prototype.cg=function(){var a=new W5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var o6,h6="",v6=q6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",lqa=q6("loadCastFramework")||q6("loadCastApplicationFramework"),Tqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(x6,g.H);g.h=x6.prototype;g.h.aD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.D)()+this.Vc:this.za=g.Hg(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();x6.Ha.T.call(this)};
g.h.bD=function(){this.l?(this.za=g.Hg(this.u,this.l-(0,g.D)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};y6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Xg=null;g.h.xe=!1;g.h.Vi=null;g.h.Ts=null;g.h.Fi=null;g.h.ai=null;g.h.kg=null;g.h.Bg=null;g.h.sh=null;g.h.tc=null;g.h.Wk=0;g.h.Be=null;g.h.fo=null;g.h.lg=null;g.h.Jj=-1;g.h.Sz=!0;g.h.Ng=!1;g.h.Op=0;g.h.yn=null;var G6={},E6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.JL=function(a){a=a.target;var b=this.yn;b&&3==M5(a)?b.Fj():this.YA(a)};
g.h.YA=function(a){try{if(a==this.tc)a:{var b=M5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Ld&&!g.nd(10)||g.Nd&&!g.md("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!P5(this.tc))break a;this.Ng||4!=b||7==c||(8==c||0>=d?this.g.re(3):this.g.re(2));Q6(this);var e=this.tc.getStatus();this.Jj=e;var f=P5(this.tc);(this.xe=200==e)?(4==b&&I6(this),this.u?(K6(this,b,f),g.Ch&&this.xe&&3==b&&(this.ba.da(this.i,"tick",this.FL),this.i.start())):H6(this,f),this.xe&&!this.Ng&&(4==b?this.g.hn(this):(this.xe=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.lg=3,F6(13)):(this.lg=0,F6(14)),I6(this),J6(this))}}catch(k){this.tc&&P5(this.tc)}finally{}};
g.h.FL=function(){var a=M5(this.tc),b=P5(this.tc);this.Wk<b.length&&(Q6(this),K6(this,a,b),this.xe&&4!=a&&D6(this))};
g.h.eL=function(a){P6((0,g.y)(this.dL,this,a),0)};
g.h.dL=function(a){this.Ng||(Q6(this),H6(this,a),D6(this))};
g.h.Xy=function(a){P6((0,g.y)(this.cL,this,a),0)};
g.h.cL=function(a){this.Ng||(I6(this),this.xe=a,this.g.hn(this),this.g.re(4))};
g.h.cancel=function(){this.Ng=!0;I6(this)};
g.h.oL=function(){this.Vi=null;var a=(0,g.D)();0<=a-this.Ts?(2!=this.ai&&this.g.re(3),I6(this),this.lg=2,F6(18),J6(this)):O6(this,this.Ts-a)};
g.h.getLastError=function(){return this.lg};g.h=U6.prototype;g.h.Mp=null;g.h.Cd=null;g.h.zn=!1;g.h.Vv=null;g.h.Ul=null;g.h.Aq=null;g.h.Np=null;g.h.be=null;g.h.yf=-1;g.h.Ij=null;g.h.dj=null;g.h.connect=function(a){this.Np=a;a=V6(this.g,null,this.Np);F6(3);this.Vv=(0,g.D)();var b=this.g.D;null!=b?(this.Ij=b[0],(this.dj=b[1])?(this.be=1,W6(this)):(this.be=2,Y6(this))):(F5(a,"MODE","init"),this.Cd=new z6(this,void 0,void 0,void 0),this.Cd.Xg=this.Mp,C6(this.Cd,a,!1,null,!0),this.be=0)};
g.h.nC=function(a){if(a)this.be=2,Y6(this);else{F6(4);var b=this.g;b.Je=b.ag.yf;r7(b,9)}a&&this.re(2)};
g.h.hp=function(a){return this.g.hp(a)};
g.h.abort=function(){this.Cd&&(this.Cd.cancel(),this.Cd=null);this.yf=-1};
g.h.Uv=function(){return!1};
g.h.Ry=function(a,b){this.yf=a.Jj;if(0==this.be)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.yf;r7(c,2);return}this.Ij=c[0];this.dj=c[1]}else c=this.g,c.Je=this.yf,r7(c,2);else if(2==this.be)if(this.zn)F6(7),this.Aq=(0,g.D)();else if("11111"==b){if(F6(6),this.zn=!0,this.Ul=(0,g.D)(),c=this.Ul-this.Vv,!g.Ld||g.nd(10)||500>c)this.yf=200,this.Cd.cancel(),F6(12),X6(this.g,this,!0)}else F6(8),this.Ul=this.Aq=(0,g.D)(),this.zn=!1};
g.h.hn=function(){this.yf=this.Cd.Jj;if(this.Cd.xe)0==this.be?this.dj?(this.be=1,W6(this)):(this.be=2,Y6(this)):2==this.be&&((!g.Ld||g.nd(10)?!this.zn:200>this.Aq-this.Ul)?(F6(11),X6(this.g,this,!1)):(F6(12),X6(this.g,this,!0)));else{0==this.be?F6(9):2==this.be&&F6(10);var a=this.g;this.Cd.getLastError();a.Je=this.yf;r7(a,2)}};
g.h.Mk=function(){return this.g.Mk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.re=function(a){this.g.re(a)};g.h=Z6.prototype;g.h.qj=null;g.h.zd=null;g.h.Sb=null;g.h.Lp=null;g.h.Wl=null;g.h.mu=null;g.h.jm=null;g.h.tk=0;g.h.pH=0;g.h.Tc=null;g.h.gg=null;g.h.lf=null;g.h.Sg=null;g.h.ag=null;g.h.co=null;g.h.ki=-1;g.h.Dw=-1;g.h.Je=-1;g.h.Uh=0;g.h.Nh=0;g.h.Og=8;var s7=new g.Rf;g.A($6,g.qf);g.A(a7,g.qf);g.A(b7,g.qf);g.h=Z6.prototype;g.h.connect=function(a,b,c,d,e){F6(0);this.Lp=b;this.qj=c||{};d&&g.Ca(e)&&(this.qj.OSID=d,this.qj.OAID=e);this.A?(P6((0,g.y)(this.Eu,this,a),100),h7(this)):this.Eu(a)};
g.h.Eu=function(a){this.ag=new U6(this);this.ag.Mp=null;this.ag.i=this.u;this.ag.connect(a)};
g.h.Uv=function(){return 0==this.g};
g.h.Wy=function(a){this.gg=null;m7(this,a)};
g.h.Vy=function(){this.lf=null;this.Sb=new z6(this,this.l,"rpc",this.B);this.Sb.Xg=null;this.Sb.Op=0;var a=this.mu.clone();g.ln(a,"RID","rpc");g.ln(a,"SID",this.l);g.ln(a,"CI",this.co?"0":"1");g.ln(a,"AID",this.ki);d7(this,a);if(!g.Ld||g.nd(10))g.ln(a,"TYPE","xmlhttp"),C6(this.Sb,a,!0,this.jm,!1);else{g.ln(a,"TYPE","html");var b=this.Sb,c=!!this.jm;b.ai=3;b.kg=E5(a.clone());N6(b,c)}};
g.h.Ry=function(a,b){if(0!=this.g&&(this.Sb==a||this.zd==a))if(this.Je=a.Jj,this.zd==a&&3==this.g)if(7<this.Og){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.lf){if(this.Sb)if(this.Sb.Fi+3E3<this.zd.Fi)i7(this),this.Sb.cancel(),this.Sb=null;else break a;p7(this);F6(19)}}else this.Dw=c[1],0<this.Dw-this.ki&&37500>c[2]&&this.co&&0==this.Nh&&!this.Sg&&(this.Sg=P6((0,g.y)(this.TH,this),6E3));else r7(this,11)}else b!=Era.GN.g&&r7(this,11);else if(this.Sb==a&&
i7(this),!g.vb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.ki=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.jm=e[2],e=e[3],null!=e?this.Og=e:this.Og=6,this.g=3,this.Tc&&this.Tc.yu(),this.mu=V6(this,this.Mk()?this.jm:null,this.Lp),n7(this)):"stop"==e[0]&&r7(this,7):3==this.g&&("stop"==e[0]?r7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.xu(e),this.Nh=0)}}};
g.h.TH=function(){null!=this.Sg&&(this.Sg=null,this.Sb.cancel(),this.Sb=null,p7(this),F6(20))};
g.h.hn=function(a){if(this.Sb==a){i7(this);this.Sb=null;var b=2}else if(this.zd==a)this.zd=null,b=1;else return;this.Je=a.Jj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.D)()-a.Fi,s7.dispatchEvent(new a7(s7,a.sh?a.sh.length:0,b,this.Uh)),g7(this),this.o.length=0):n7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.zd||this.gg||1==this.g||2<=this.Uh?d=!1:(this.gg=P6((0,g.y)(this.Wy,this,a),o7(this,this.Uh)),this.Uh++,d=!0);d=!(d||2==b&&p7(this))}if(d)switch(c){case 1:r7(this,
5);break;case 4:r7(this,10);break;case 3:r7(this,6);break;case 7:r7(this,12);break;default:r7(this,2)}}};
g.h.DC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.nM=function(a){a?F6(2):(F6(1),q7(this,8))};
g.h.hp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.re=function(a){s7.dispatchEvent(new b7(s7,a))};
g.h.Mk=function(){return!(!g.Ld||g.nd(10))};
g.h=t7.prototype;g.h.yu=function(){};
g.h.xu=function(){};
g.h.wu=function(){};
g.h.Uo=function(){};
g.h.zv=function(){return{}};
g.h.isActive=function(){return!0};g.A(u7,g.H);g.h=u7.prototype;g.h.WK=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.xo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.A(v7,t7);g.h=v7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Hf=function(a){return this.l.Yg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.of(this.l),w7(this),g.of(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new Z6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ki):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):x7(this)&&j7(this.g,c)};
g.h.yu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)j7(this.g,a[b])}this.N("handlerOpened")};
g.h.wu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Uo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.zv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.dc(a,this.u);return a};
g.h.xu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),f7(this.g)):this.N("handlerMessage",new pqa(a[0],a[1]))};
g.h.SL=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.zd&&b++;0==b&&this.connect(this.u,this.o)};y7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
y7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
y7.prototype.u=function(a){a(Error("request timed out"))};var wqa=(0,g.D)(),D7=null,G7=Array(50),F7=-1,H7=!1;g.A(I7,g.Q);I7.prototype.Id=function(){return this.g};
I7.prototype.contains=function(a){return!!d6(this.g,a)};
I7.prototype.get=function(a){return a?e6(this.g,a):null};
I7.prototype.info=function(a){E7(this.B,a)};g.A(J7,g.Q);var Fra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=J7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.bB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.aq(this.za),this.za=NaN)};
g.h.T=function(){this.stop();J7.Ha.T.call(this)};
g.h.bB=function(){this.za=NaN;this.g=g.Wq(z7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.KM,this),onError:(0,g.y)(this.JM,this),qd:(0,g.y)(this.LM,this)})};
g.h.KM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new X5(c))};
g.h.JM=function(a){this.g=null;a.status&&404==a.status?this.i>=Fra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=Fra[this.i],this.za=g.Zp((0,g.y)(this.bB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.LM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(L7,I7);g.h=L7.prototype;g.h.start=function(){K7(this)&&this.N("screenChange");!g.xt("yt-remote-lounge-token-expiration")&&Aqa(this);g.aq(this.i);this.i=g.Zp((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){K7(this);xqa(this,a);M7(this,!1);this.N("screenChange");b(a);a.token||Aqa(this)};
g.h.remove=function(a,b){var c=K7(this);zqa(this,a)&&(M7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Yn=function(a,b,c,d){var e=K7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,M7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.aq(this.i);L7.Ha.T.call(this)};
g.h.lD=function(a){K7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}M7(this,!b);b&&E7(this.B,"Missed "+b+" lounge tokens.")};
g.h.kD=function(a){E7(this.B,"Requesting lounge tokens failed: "+a)};g.A(O7,g.Q);g.h=O7.prototype;g.h.start=function(){var a=parseInt(g.xt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?Q7(this):(this.o=(0,g.D)()+3E5,g.wt("yt-remote-fast-check-period",this.o),this.Sr())};
g.h.isEmpty=function(){return g.Wb(this.g)};
g.h.update=function(){N7("Updating availability on schedule.");var a=this.A(),b=g.Kb(this.g,function(c,d){return c&&!!e6(a,d)},this);
P7(this,b)};
g.h.T=function(){g.aq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);O7.Ha.T.call(this)};
g.h.Sr=function(){g.aq(this.l);this.l=NaN;this.i&&this.i.abort();var a=Dqa(this);if(R5(a)){var b=z7(this.u,"/pairing/get_screen_availability");this.i=A7(this.u,b,{lounge_token:g.Qb(a).join(",")},(0,g.y)(this.AK,this,a),(0,g.y)(this.zK,this))}else P7(this,{}),Q7(this)};
g.h.AK=function(a,b){this.i=null;var c=g.Qb(Dqa(this));if(g.qb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;P7(this,d);Q7(this)}else this.Jb("Changing Screen set during request."),this.Sr()};
g.h.zK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;Q7(this)};
g.h.Jb=function(a){E7("OnlineScreenService",a)};g.A(R7,I7);g.h=R7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Yn=function(a,b,c,d){this.l.contains(a)?this.l.Yn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,E7(this.B,a),d(Error(a)))};
g.h.Id=function(a){return a?this.g:g.eb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.cB=function(){return(0,g.Xd)(this.Id(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.dB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new J7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.of(f);d(S7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.of(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.OM=function(a,b,c,d){g.Wq(z7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new X5(f.screen||{});if(!k.name||Hqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Hqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(S7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
qd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.of(this.l);g.of(this.i);R7.Ha.T.call(this)};
g.h.uD=function(){Iqa(this);this.N("screenChange");this.i.update()};
R7.prototype.dispose=R7.prototype.dispose;g.A(U7,g.Q);g.h=U7.prototype;g.h.jn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Md=function(a){this.ea()||(a&&V7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){E7(this.P,a)};
g.h.fB=function(){return null};
g.h.gs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){V7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.gs("");U7.Ha.T.call(this)};g.A(W7,U7);g.h=W7.prototype;g.h.es=function(a){if(this.g){if(this.g==a)return;V7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Kqa(this)};
g.h.mi=function(a){this.info("launchWithParams no-op for Cast: "+g.Lg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Md()},this),(0,g.y)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.gs=g.Ga;g.h.T=function(){this.info("disposeInternal");g.aq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;W7.Ha.T.call(this)};
g.h.zL=function(a,b){if(!this.ea())if(b){var c=T5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Lg(c));switch(d){case "mdxSessionStatus":Jqa(this,c.screenId);break;default:V7(this,"Unknown youtube message: "+d)}}else V7(this,"Unable to parse message.")}else V7(this,"No data in message.")};
g.h.Ov=function(a,b,c,d){Gqa(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(V7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Zp((0,g.y)(this.Ov,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.fB=function(){return this.g};
g.h.PM=function(a){this.ea()||a||(V7(this,"Cast session died."),this.Md())};g.A(X7,U7);g.h=X7.prototype;g.h.es=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.mi=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ga;g.aq(this.A);this.o?this.o.stop((0,g.y)(this.Md,this,null),(0,g.y)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.T=function(){this.g();this.g=g.Ga;g.aq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;X7.Ha.T.call(this)};
g.h.SM=function(a){this.ea()||a||(V7(this,"DIAL session died."),this.g(),this.g=g.Ga,this.Md())};
g.h.bq=function(a){this.H=c6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Mqa(this));a(b);Lqa(this)}else this.B=(0,g.y)(function(){g.aq(this.A);this.B=g.Ga;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Mqa(this));a(c);Lqa(this)},this),this.A=g.Zp((0,g.y)(function(){this.B()},this),100)};
g.h.SD=function(a,b,c){Gqa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.jn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.bq(b,c)},this),(0,g.y)(function(d){V7(this,"Failed to get DIAL screen: "+d);
this.bq(b,c)},this))};g.A(Y7,U7);Y7.prototype.stop=function(){this.Md()};
Y7.prototype.es=g.Ga;Y7.prototype.mi=function(){g.aq(this.g);this.g=NaN;var a=e6(this.F.Id(),this.i.label);a?this.jn(a):this.Md(Error("No such screen"))};
Y7.prototype.T=function(){g.aq(this.g);this.g=NaN;Y7.Ha.T.call(this)};g.A(Z7,g.Q);g.h=Z7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.Ty,this),(0,g.y)(this.jK,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.tI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),tqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.eB,this)),this.l=Oqa(this),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Lg(f))},this)),this.N("yt-remote-cast2-availability-change",a8(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Lg(f));
b(!1)},this))};
g.h.bM=function(a,b){$7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)$7("Unsetting old screen status: "+this.g.i.friendlyName),b8(this,null)}if(a&&b){if(!this.g){c=e6(this.i.Id(),a);if(!c){$7("setConnectedScreenStatus: Unknown screen.");return}var d=Nqa(this,c);d||($7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ga,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Lg(e))},this)));
$7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);b8(this,new Y7(this.i,d),!0)}this.g.gs(b)}else $7("setConnectedScreenStatus: no screen.")};
g.h.cM=function(a){this.ea()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.mi(a):this.Jb("Setting connection data without a session")};
g.h.RM=function(){this.ea()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),b8(this,null)):$7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.Ty,this),(0,g.y)(this.FK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.eB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],B7);g.of(this.g);Z7.Ha.T.call(this)};
g.h.Jb=function(a){E7("Controller",a)};
g.h.Uy=function(a,b){this.g==a&&(b||b8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.fK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),$7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)$7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{$7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:b8(this,
new Y7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:b8(this,new X7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:b8(this,new W7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.tI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return $7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);b8(this,new X7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.SD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.bq,b))};
g.h.Ty=function(a){if(!this.ea()){$7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)$7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),b8(this,new W7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=e6(this.i.Id(),c.label);d&&Y5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&($7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.of(this.g),this.g=new W7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Uy,this,this.g)),this.g.mi(null));this.g.es(a)}}};
g.h.QM=function(){return this.g?this.g.fB():null};
g.h.FK=function(a){this.ea()||(this.Jb("Failed to estabilish a session: "+g.Lg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&b8(this,null))};
g.h.jK=function(a){$7("Receiver availability updated: "+a);if(!this.ea()){var b=a8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;a8(this)!=b&&this.N("yt-remote-cast2-availability-change",a8(this))}};
g.h.eB=function(){this.ea()||(this.l=Oqa(this),$7("Updating custom receivers: "+g.Lg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",a8(this)))};
Z7.prototype.setLaunchParams=Z7.prototype.cM;Z7.prototype.setConnectedScreenStatus=Z7.prototype.bM;Z7.prototype.stopSession=Z7.prototype.RM;Z7.prototype.getCastSession=Z7.prototype.QM;Z7.prototype.requestSession=Z7.prototype.requestSession;Z7.prototype.init=Z7.prototype.init;Z7.prototype.dispose=Z7.prototype.dispose;var h8=[];m8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";n8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Le=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
m8.prototype.isAdPlaying=function(){return 1081==this.playerState};
m8.prototype.getDuration=function(){return this.u?this.D+o8(this):this.D};
m8.prototype.clone=function(){return new m8(s8(this))};g.A(u8,g.Q);g.h=u8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ga,A8(this,"play")):z8(this,"play"),y8(this,1,q8(v8(this))),this.N("remotePlayerChange")):w8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ga,A8(this,"pause")):z8(this,"pause"),y8(this,2,q8(v8(this))),this.N("remotePlayerChange")):w8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=v8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ga,A8(this,"seekTo",{newTime:a}))}else z8(this,"seekTo",{newTime:a});y8(this,3,a);this.N("remotePlayerChange")}else w8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ga,A8(this,"stopVideo")):z8(this,"stopVideo");var a=v8(this);a.index=-1;a.videoId="";n8(a);x8(this,a);this.N("remotePlayerChange")}else w8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=v8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){E7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){E7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);z8(this,"setVolume",e)}c.muted=b;c.volume=a;x8(this,c)}else w8(this,g.Qa(this.setVolume,a,b))};
g.h.fA=function(a,b){if(1==this.g){var c=v8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Lg(b.style),g.dc(d,c.g));z8(this,"setSubtitlesTrack",d);x8(this,c)}else w8(this,g.Qa(this.fA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();z8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=v8(this);d.audioTrackId=c;x8(this,d)}else w8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=v8(this);c=c||0;var m={videoId:a,currentIndex:c};r8(l,a,c);g.Ca(b)&&(p8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Lg(k));z8(this,"setPlaylist",m);d||x8(this,l)};
g.h.un=function(a,b){if(1==this.g){if(a&&b){var c=v8(this);r8(c,a,b);x8(this,c)}z8(this,"previous")}else w8(this,g.Qa(this.un,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=v8(this);r8(c,a,b);x8(this,c)}z8(this,"next")}else w8(this,g.Qa(this.nextVideo,a,b))};
g.h.Xu=function(){1==this.g?z8(this,"dismissAutoplay"):w8(this,this.Xu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}u8.Ha.dispose.call(this)};
g.h.T=function(){ara(this);this.o=null;this.u.clear();t8(this,null);u8.Ha.T.call(this)};
g.h.Ws=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.cK=function(a,b){this.N(a,b)};
g.h.ZH=function(a){if(!a)this.wk(null),t8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=v8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)E7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,x8(this,b)}};
g.h.wk=function(a){E7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),bra(this),this.N("remotePlayerChange")};
g.h.YH=function(a){a?(bra(this),this.N("remotePlayerChange")):this.wk(null)};
g.h.Fs=function(){z8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.lI=function(){var a=Yqa();a&&t8(this,a)};
g.h.Jb=function(a){E7("CP",a)};g.A(B8,g.Q);g.h=B8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;p8(this.Pa,m);this.o="UNSUPPORTED";C8("Connecting with setPlaylist and params: "+g.Lg(l));this.g.connect({method:"setPlaylist",
params:g.Lg(l)},a,k6())}else C8("Connecting without params"),this.g.connect({},a,k6());dra(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),D8(this,3));B8.Ha.dispose.call(this)};
g.h.T=function(){E8(this);G8(this);F8(this);g.aq(this.F);this.F=NaN;g.aq(this.H);this.H=NaN;this.l=null;g.ds(this.O);this.O.length=0;this.g.dispose();B8.Ha.T.call(this);this.o=this.B=this.i=this.Pa=this.g=null};
g.h.eD=function(){this.A(2)};
g.h.dI=function(){C8("Channel opened");this.M&&(this.M=!1,F8(this),this.P=g.Zp((0,g.y)(function(){C8("Timing out waiting for a screen.");this.A(1)},this),15E3));
jqa(qqa(this.g),this.V)};
g.h.aI=function(){C8("Channel closed");isNaN(this.u)?n6(!0):n6();this.dispose()};
g.h.bI=function(a){n6();isNaN(this.D())?(C8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,C8("Channel error: "+a+" with reconnection in "+this.D()+" ms"),D8(this,2))};
g.h.cI=function(a){a.params?C8("Received: action="+a.action+", params="+g.Lg(a.params)):C8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=T5(a.params.devices);this.i=(0,g.G)(a,function(c){return new W5(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
gra(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
gra(this,!1);break;case "remoteConnected":var b=new W5(T5(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||Ypa(this.i,b);
break;case "remoteDisconnected":b=new W5(T5(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":ira(this,a);break;case "nowPlaying":kra(this,a);break;case "onStateChange":jra(this,a);break;case "onAdStateChange":lra(this,a);break;case "onVolumeChanged":mra(this,a);break;case "onSubtitlesTrackChanged":hra(this,a);break;case "nowAutoplaying":nra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":ora(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:C8("Unrecognized action: "+a.action)}};
g.h.PL=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&H8(this,"getNowPlaying")}};
B8.prototype.subscribe=B8.prototype.subscribe;B8.prototype.unsubscribeByKey=B8.prototype.Hf;B8.prototype.ca=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?x7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
B8.prototype.getProxyState=B8.prototype.ca;B8.prototype.A=function(a){C8("Disconnecting with "+a);E8(this);this.N("beforeDisconnect",a);1==a&&n6();w7(this.g,a);this.dispose()};
B8.prototype.disconnect=B8.prototype.A;B8.prototype.X=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),r8(a,this.l,a.index));return s8(a)};
B8.prototype.getPlayerContextData=B8.prototype.X;
B8.prototype.ka=function(a){var b=new m8(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.aq(this.F),this.F=g.Zp((0,g.y)(this.PL,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&q8(this.Pa)==q8(b)&&g.Lg(this.Pa.g)==g.Lg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
B8.prototype.setPlayerContextData=B8.prototype.ka;B8.prototype.R=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
B8.prototype.getOtherConnectedRemoteId=B8.prototype.R;B8.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
B8.prototype.getReconnectTimeout=B8.prototype.D;B8.prototype.aa=function(){return this.o||"UNSUPPORTED"};
B8.prototype.getAutoplayMode=B8.prototype.aa;B8.prototype.Z=function(){return this.B||""};
B8.prototype.getAutoplayVideoId=B8.prototype.Z;B8.prototype.va=function(){if(!isNaN(this.D())){var a=this.g.i;g.yo(a.g);a.start()}};
B8.prototype.reconnect=B8.prototype.va;B8.prototype.ia=function(a,b){H8(this,a,b);fra(this)};
B8.prototype.sendMessage=B8.prototype.ia;g.A(I8,I7);g.h=I8.prototype;g.h.Id=function(a){return this.Hc.$_gs(a)};
g.h.contains=function(a){return!!this.Hc.$_c(a)};
g.h.get=function(a){return this.Hc.$_g(a)};
g.h.start=function(){this.Hc.$_st()};
g.h.add=function(a,b,c){this.Hc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Hc.$_r(a,b,c)};
g.h.Yn=function(a,b,c,d){this.Hc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hc.$_ubk(this.i[a]);this.i.length=0;this.Hc=null;I8.Ha.T.call(this)};
g.h.MM=function(){this.N("screenChange")};
g.h.GJ=function(){this.N("onlineScreenChange")};
R7.prototype.$_st=R7.prototype.start;R7.prototype.$_gspc=R7.prototype.OM;R7.prototype.$_gsppc=R7.prototype.dB;R7.prototype.$_c=R7.prototype.contains;R7.prototype.$_g=R7.prototype.get;R7.prototype.$_a=R7.prototype.add;R7.prototype.$_un=R7.prototype.Yn;R7.prototype.$_r=R7.prototype.remove;R7.prototype.$_gs=R7.prototype.Id;R7.prototype.$_gos=R7.prototype.cB;R7.prototype.$_s=R7.prototype.subscribe;R7.prototype.$_ubk=R7.prototype.Hf;var J8=null,K8=null,Z8=null,O8=[];g.t($8,g.H);g.h=$8.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Qy,this);this.g.unsubscribe("remotePlayerChange",this.yk,this);this.g.unsubscribe("remoteQueueChange",this.kn,this);this.g.unsubscribe("autoplayUpNext",this.ty,this);this.g.unsubscribe("previousNextChange",this.Ny,this);this.g.unsubscribe("nowAutoplaying",this.Jy,this);this.g.unsubscribe("autoplayDismissed",this.ry,this);this.g=this.u=null};
g.h.qx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(c9(this)){if(!v8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==v8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Fj(c[0],c[1]);break;case "control_subtitles_set_track":d9(this,c[0]);break;case "control_set_audio_track":c=c[0],c9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();e9(this,0==c?void 0:c);break;case "control_seek":e9(this,c[0]);break;case "control_subtitles_set_track":d9(this,c[0]);break;case "control_set_audio_track":c=c[0],c9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.XH=function(a){this.I.aD(a)};
g.h.wM=function(a){this.qx("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.rA=function(){var a=this.i.getOption("captions","track");g.Wb(a)||d9(this,a)};
g.h.Fy=function(a){if(c9(this)){this.g.unsubscribe("remotePlayerChange",this.yk,this);var b=Math.round(a.volume);a=!!a.muted;var c=v8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.yk,this)}};
g.h.YI=function(){g.Wb(this.B)||Ara(this,this.B);this.D=!1};
g.h.Qy=function(a,b){this.A.stop();2==b&&this.qA()};
g.h.yk=function(){if(c9(this)){this.o.stop();var a=v8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Bm=1;break;case 1082:case 1083:this.u.Bm=0;break;default:this.u.Bm=-1}switch(a.playerState){case 1081:case 1:b9(this,new g.yC(8));this.pA();break;case 1085:case 3:b9(this,new g.yC(9));break;case 1083:case 0:b9(this,new g.yC(2));this.H.stop();a9(this,this.i.getVideoData().lengthSeconds);break;case 1084:b9(this,new g.yC(4));break;case 2:b9(this,new g.yC(4));a9(this,q8(a));
break;case -1:b9(this,new g.yC(64));break;case -1E3:b9(this,new g.yC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=v8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,Ara(this,a));a=v8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.PA()}else zra(this)};
g.h.Ny=function(){this.i.N("mdxpreviousnextchange")};
g.h.kn=function(){c9(this)||zra(this)};
g.h.mC=function(){this.g.Xu()};
g.h.ty=function(a){a&&(a=g.Wq("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.hL,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.hL=function(a,b){var c=new g.jB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Jy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.ry=function(){this.i.N("mdxautoplaycanceled")};
g.h.DF=function(a,b){-1==v8(this.g).playerState?e9(this,a):b&&this.g.seekTo(a)};
g.h.PA=function(){if(c9(this)){var a=v8(this.g);this.l.Ma(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Fy)}};
g.h.pA=function(){this.o.stop();if(!this.g.ea()){var a=v8(this.g);1==a.playerState&&b9(this,new g.yC(8));a9(this,q8(a));this.o.start()}};
g.h.qA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(f9,g.W);f9.prototype.o=function(){this.l.hide()};
f9.prototype.A=function(){this.l.hide()};g.t(g9,g.W);g9.prototype.u=function(a){Cra(this,a.state)};g.t(h9,g.WT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.sb(a,this.A,this),g.XT(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.qe(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.pe=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
h9.prototype.Jc=function(a){g.WT.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.RK);g.h=i9.prototype;g.h.create=function(){tra(g.Ty(g.X(this.player)));this.u.push(g.fq("yt-remote-before-disconnect",this.UH,this));this.u.push(g.fq("yt-remote-connection-change",this.kK,this));this.u.push(g.fq("yt-remote-receiver-availability-change",this.Oy,this));this.u.push(g.fq("yt-remote-auto-connect",this.iK,this));this.u.push(g.fq("yt-remote-receiver-resumed",this.hK,this));this.Oy()};
g.h.load=function(){this.player.cancelPlayback();g.RK.prototype.load.call(this);this.o=new $8(this,this.player,this.g);var a=(a=yra())?a.currentTime:0;var b=Y8()?new u8(T8(),void 0):null;0==a&&b&&(a=q8(v8(b)));0!=a&&this.rd(a);Bra(this,this.ek,this.ek);g.WX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.pf(this.o,this.g);this.g=this.o=null;g.RK.prototype.unload.call(this);g.WX(this.player.app,5)};
g.h.T=function(){g.gq(this.u);g.RK.prototype.T.call(this)};
g.h.Xe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.qx.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Bm};
g.h.WC=function(){return this.loaded?this.o.suggestion:null};
g.h.Le=function(){return this.g?v8(this.g).Le:!1};
g.h.hasNext=function(){return this.g?v8(this.g).hasNext:!1};
g.h.rd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=v8(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+o8(a):a.l,isAtLiveHead:1>=(a.u?a.i+o8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+o8(a):a.i,seekableStart:0<a.o?a.o+
o8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.un=function(){this.g&&this.g.un()};
g.h.UH=function(a){1==a&&(this.B=this.g?v8(this.g):null)};
g.h.kK=function(){var a=Y8()?new u8(T8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.of(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,q8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Oy=function(){this.A=[this.i].concat(vra());var a=U8()||this.i;j9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.iK=function(){var a=U8();j9(this,a)};
g.h.hK=function(){this.l=U8()};
g.h.Zb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?k8():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&k8(),!0):!1}};
g.h.Fs=function(){this.g.Fs()};
g.h.Ib=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.mV.remote=i9;})(_yt_player);
